name: MagnetRelay
options:
  bundleIdPrefix: com.magnetrelay
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "2"
  DEVELOPMENT_TEAM: "76ZSP26L92"

targets:
  MagnetRelay:
    type: application
    platform: macOS
    sources:
      - path: MagnetRelay
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.magnetrelay.app
      INFOPLIST_FILE: MagnetRelay/Info.plist
      CODE_SIGN_ENTITLEMENTS: MagnetRelay/MagnetRelay.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      COMBINE_HIDPI_IMAGES: YES
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "Apple Development"
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    entitlements:
      path: MagnetRelay/MagnetRelay.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
